### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Siddhart2004**
added my project

### CODE REVIEW

**Comment by Siddhart2004** [comment]
@Snehsk kindly merge my pr.

**Review by Snehsk — CHANGES_REQUESTED** [review]
Please rename the screenshot as this format 

> Name-projectname-date

**Comment by Siddhart2004** [comment]
@Snehsk made the changes.

**Review by Snehsk — APPROVED** [review]

**Review by Snehsk — COMMENTED** [review]
🚀 Congratulations for your submission, your points will be reflected in the leaderboard till tomorrow.

**Pull request merged**
