### PR TITLE
added my SmartGuard file 

### PR DESCRIPTION
**Pull request by 23wh1a12c1**

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Please Submit the Screenshot in jpg format.

**Create a new PR** 
image

**Comment by 23wh1a12c1** [comment]
How do I do that?

**Comment by aslams2020** [comment]
Just Upload the screenshot of it.
rename that ss as - `name-projectname-date`

You can make a New PR it'll be easy

**Comment by 23wh1a12c1** [comment]
Meghana_SmartGuard_2Nov

**Comment by 23wh1a12c1** [comment]
i am unable to upload again
how ?

**Comment by 23wh1a12c1** [comment]
i am unable to upload again can u give access for this

**Comment by aslams2020** [comment]
hi @23wh1a12c1 , Follow these steps: 
1. Fork this repository.
2. Go to `submit` folder 
3. Add your screenshot there (ss name : `name-projectname-date` 
4. Create a pull request 

It seems that you haven't forked the repo yet after I reviewed ur profile. 

Will close this PR now,

**Comment by 23wh1a12c1** [comment]
I have uploaded can u please once check and tell me confirmation. Is that
correct ?

**Pull request closed without merging**
