### PR TITLE
add my repo filr

### PR DESCRIPTION
**Pull request by Tanisha0708**

### CODE REVIEW

**Comment by Tanisha0708** [comment]
@sanjay-kv  please  once go through this pr

**Review by Snehsk — CHANGES_REQUESTED** [review]
Please add png file and rename the screenshot as this format 
Name-projectname-date 

Keep only one image so delete previous file.

**Comment by Tanisha0708** [comment]
Tanisha Chavan - Social media manager-08-11-2024 png

**Comment by Tanisha0708** [comment]
@Snehsk  here is the some changes did in the file please once go throught this pr

**Comment by aslams2020** [comment]
This PR cannot be merged. You have to add a screenshot of the dashboard only.
No need to create .html file

**Comment by aslams2020** [comment]
Create a new PR

**Pull request closed without merging**
