### PR TITLE
added my Hack web3 Build submission file

### PR DESCRIPTION
**Pull request by shriyadindi**
shriyadindi-designcafe_2nov

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
There is No Screenshot uploaded in this PR. Add the screenshot

**Review by aslams2020 — CHANGES_REQUESTED** [review]
image

**Review by shriyadindi — COMMENTED** [review]
shriyadindi-designcafe_2nov

**Comment by aslams2020** [comment]
@shriyadindi It should be there in the PR. 
So that After merging your image should be there in repo. Create a New PR or edit this

**Review by aslams2020 — APPROVED** [review]

**Review by aslams2020 — COMMENTED** [review]
Congratulations for your submission! your scores will get reflected in next server update! ⚡

**Pull request merged**
