### PR TITLE
Create Attaching screenshoot

### PR DESCRIPTION
**Pull request by vcerpasalas**
Attaching link of my issue. I sent by email the screenshot and commented it

### CODE REVIEW

**Comment by vcerpasalas** [comment]
https://github.com/GSSoC24/Postman-Challenge/pull/4285

**Comment by Meetjain1** [comment]
#735 Already merged , This is duplicate pr hence closing it ! @vcerpasalas

**Comment by vcerpasalas** [comment]
@Meetjain1  I just a saw the leaderboard. Didn't receive points for my last PR merged (Postman challenge) . Is it going to be updated with this lasts PR?

**Comment by Meetjain1** [comment]
> @Meetjain1 I just a saw the leaderboard. Didn't receive points for my last PR merged (Postman challenge) . Is it going to be updated with this lasts PR?

@vcerpasalas 
This doesnt mean you create a new pr , you should inform about it to us if someone didnt noticed your both prs points will be added in the leaderboard.

For your merged pr,
Leaderboard is not updated yet, once it gets updated it will be shown on the leaderboard .

**Comment by vcerpasalas** [comment]
Thank you so much.

**Pull request closed without merging**
