### PR TITLE
 Sathvigaa Bharathi-Decentralised voting system-08/11/2024

### PR DESCRIPTION
**Pull request by SathvigaaBharathi**
WhatsApp Image 2024-11-08 at 6 24 38 PM

### CODE REVIEW

**Comment by SathvigaaBharathi** [comment]
add my PR

**Review by AKSHITHA-CHILUKA — CHANGES_REQUESTED** [review]
I am unable to see you png image

**Comment by SathvigaaBharathi** [comment]
image
i have added my screenshot which shows the uploaded image...

**Comment by AKSHITHA-CHILUKA** [comment]
image
this is what you have uploaded so please open a new pr and upload it

**Pull request closed without merging**
