### PR TITLE
Tanisha Chavan - Social media manager-08-11-2024..png add my repo file

### PR DESCRIPTION
**Pull request by Tanisha0708**

### CODE REVIEW

**Comment by Tanisha0708** [comment]
Tanisha Chavan - Social media manager-08-11-2024 png

**Comment by Tanisha0708** [comment]
@aslams2020  once go through this pr

**Comment by vansh-codes** [comment]
You have to add only 1 screenshot named `name-projectname-date`
please remove all other screenshots

**Comment by AKSHITHA-CHILUKA** [comment]
@Tanisha0708 
image
This is the crt file so open a new pr and just add this image file in it 
I am closing this pr so open a new pr

**Pull request closed without merging**
