### PR TITLE
Added the ss of the my buidl Hack Web3Conf India

### PR DESCRIPTION
**Pull request by Kritika75**
added my project

description:
Developed an NFT marketplace enabling users to mint, buy, and sell digital assets (e.g., art, music) with secure blockchain transactions via Web3.py and Solidity smart contracts. Utilized IPFS for asset storage and Django/Flask for user and transaction management

### CODE REVIEW

**Comment by Kritika75** [comment]
@Snehsk can you merge this?

**Review by Snehsk — CHANGES_REQUESTED** [review]
Could you please rename the screenshot as this format 

> Name-projectname-date

**Review by Kritika75 — COMMENTED** [review]
KritikaSingh-NFTMarketplace-06-11-24

**Comment by Kritika75** [comment]
> Could you please rename the screenshot as this format
> 
> > Name-projectname-date

Hey, I have done it, can you check now?

**Comment by Snehsk** [comment]
> > Could you please rename the screenshot as this format
> > > Name-projectname-date
> 
> @Snehsk Hey, I have done it, can you check now?

Hi could you please remove previous file.
Keep one image only

**Pull request closed without merging**
