### PR TITLE
Register For the Hackweb3

### PR DESCRIPTION
**Pull request by ishivansmishra**
added my repo file 

Please check and merge My PR and give me the badge of HACKWEB3

[shivansh mishra-firstgame-06 11 2024](https://github.com/user-attachments/assets/c3da12fd-3592-4cd6-b161-9f480ae9d4f2)

### CODE REVIEW

**Comment by ishivansmishra** [comment]
@aslams2020 Please check my PR and Merge it under the Gssoc _EXT and Hackweb3 label

**Comment by ishivansmishra** [comment]
@MastanSayyad @sanjay-kv @aslams2020 please check my PR and merge it under gssoc-ext and hackweb3 label

**Comment by ishivansmishra** [comment]
@Snehsk  please review and merge it

**Review by Snehsk — CHANGES_REQUESTED** [review]
Please rename the screenshot as this format 

> Name-projectname-date

**Comment by ishivansmishra** [comment]
@Snehsk I change the name of the screenshot

**Pull request closed without merging**
