### PR TITLE
added my repo file

### PR DESCRIPTION
**Pull request by gurramkarthiknetha**
image

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
**Add the Screenshot of the Dashboard Only.**
Also, please Remove the current screenshot.

**Comment by gurramkarthiknetha** [comment]
> **Add the Screenshot of the Dashboard Only.** Also, please Remove the current screenshot.

image

**Review by aslams2020 — APPROVED** [review]

**Comment by aslams2020** [comment]
Congratulations for your submission! your scores will get reflected in next server update! ⚡

**Pull request merged**
