### PR TITLE
added my repo file

### PR DESCRIPTION
**Pull request by NavikaAgarwal**
Screenshot 2024-11-03 200950

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Please submit the Screenshot of the Dashboard with the Project Details.

**Comment by NavikaAgarwal** [comment]
Screenshot 2024-11-04 125821

**Comment by aslams2020** [comment]
@NavikaAgarwal Add it in the PR. 
and remove the other image.

**Comment by NavikaAgarwal** [comment]
ok

**Pull request closed without merging**
