### PR TITLE
Add files via uploadAdded my file to repo

### PR DESCRIPTION
**Pull request by meghanakn473**

### CODE REVIEW

**Comment by meghanakn473** [comment]
meghana-reduce carbon footrpint
@sanjay-kv please review and merge

**Review by Snehsk — CHANGES_REQUESTED** [review]
Please rename of screenshot In this Format  
>   name-projectname-date

**Review by aslams2020 — APPROVED** [review]

**Review by aslams2020 — COMMENTED** [review]
Congratulations for your submission! your scores will get reflected in next server update! ⚡

**Comment by meghanakn473** [comment]
> Congratulations for your submission! your scores will get reflected in next server update! ⚡

@MastanSayyad i was assigned only 250 points to this pr, please check it is said that 500 points will be assigned right?

**Comment by aslams2020** [comment]
Everyone will get 500 points for this PR. There's no codebase for 250 points.
check correctly

**Pull request merged**
