### PR TITLE
updated

### PR DESCRIPTION
**Pull request by Chinmayee-cd**
here is the link: https://github.com/Chinmayee-cd/Hack-Web3Conf/pull/1

### CODE REVIEW

**Comment by AKSHITHA-CHILUKA** [comment]
open a new pr

**Comment by Meetjain1** [comment]
@Chinmayee-cd open a new pr

**Comment by Chinmayee-cd** [comment]
I added my ss for the pull request in the Postman Challenge repo

**Comment by AKSHITHA-CHILUKA** [comment]
yes open a new pr

**Pull request closed without merging**
