### PR TITLE
Screenshot Submitted

### PR DESCRIPTION
**Pull request by TusharKale10**
Hello @Molza01 , @DevROHIT11  these are my teammates for hack web3conf they are also part of gssoc'24 extd and we are working as a team !! so please accept our request .

### CODE REVIEW

**Review by AKSHITHA-CHILUKA — CHANGES_REQUESTED** [review]
please rename your file and submit

**Comment by AKSHITHA-CHILUKA** [comment]
Rename it as your name - project title - date

**Comment by TusharKale10** [comment]
i have rename it as you  said ;in new PR plz check it and kindly accept my request

**Comment by AKSHITHA-CHILUKA** [comment]
image
rename this file @TusharKale10
image

**Pull request closed without merging**
