### PR TITLE
Add my BUILD

### PR DESCRIPTION
**Pull request by smog-root**
Add all labels.. @aslams2020

### CODE REVIEW

**Review by Snehsk — CHANGES_REQUESTED** [review]
Please rename the screenshot as this format:

> name-projectname-date

**Comment by smog-root** [comment]
@Snehsk I'm closing this PR.. Merge my PR first.. because I have submitted it first!!

Closing due to I can't change the file name now!!

**Comment by aslams2020** [comment]
@smog-root Everyone's PRs will be merged. The sequence will not matter. Create a new PR with corrected image.

**Comment by smog-root** [comment]
I created #208

**Comment by aslams2020** [comment]
Okay! @Snehsk will merge it.

**Comment by Snehsk** [comment]
> Okay! @Snehsk will merge it.

Will the date be today or it is of yesterday 4?

**Comment by aslams2020** [comment]
We will give priority to 'name-projectname' ig...Date will be there in record of project files. 
Chlega hum krdete hai merge. 'Name-projectname' rha to bhi...to avoid confusion.

**Comment by smog-root** [comment]
@Snehsk yesterday.. because I have raised the PR yesterday!!

**Comment by Snehsk** [comment]
> We will give priority to 'name-projectname' ig...Date will be there in record of project files. Chlega hum krdete hai merge. 'Name-projectname' rha to bhi...to avoid confusion.

Ok @aslams2020 you can do this.👍

**Comment by smog-root** [comment]
@aslams2020 I raised the PR yesterday!!

**Comment by smog-root** [comment]
Merge it #208 @aslams2020 @Snehsk

**Pull request closed without merging**
