### PR TITLE
added my Repo File

### PR DESCRIPTION
**Pull request by KrishChothani**

### CODE REVIEW

**Comment by KrishChothani** [comment]
Hey @Snehsk ,
Plz add This Pr ....
and if any issues , let me know 

Thank you...

**Review by Snehsk — CHANGES_REQUESTED** [review]
Please rename the screenshot as this format 

> Name-projectname-date

**Comment by KrishChothani** [comment]
Hey @Snehsk 
You can check it. 

Thank you ....

**Review by Snehsk — APPROVED** [review]

**Review by Snehsk — COMMENTED** [review]
🚀 Congratulations for your submission, your points will be reflected in the leaderboard till tomorrow.

**Pull request merged**
