### PR TITLE
Added my repo file

### PR DESCRIPTION
**Pull request by pinakviramgama**

### CODE REVIEW

**Comment by pinakviramgama** [comment]
Dear @Snehsk , i have created this pull request for ranaming the screenschot, please approe it.

**Comment by Snehsk** [comment]
> Dear @Snehsk , i have created this pull request for ranaming the screenschot, please approe it.

Please delete previous image.

**Comment by pinakviramgama** [comment]
mam how to delete ?

**Comment by Snehsk** [comment]
> mam how to delete ?

Click on 3 dot 
Have you got delete option

**Comment by pinakviramgama** [comment]
mam github is not authorising me delete the file

**Comment by pinakviramgama** [comment]
mam now what should i do ?

**Comment by Snehsk** [comment]
> mam now what should i do ?

Close this pr and create new and this time please upload only one image

**Comment by pinakviramgama** [comment]
ok mam

**Review by pinakviramgama — COMMENTED** [review]
viewed

**Pull request closed without merging**
