### PR TITLE
Added My Project File

### PR DESCRIPTION
**Pull request by AkCode2005**
My project is submitted to HackWeb3Conf.
Please Go through It 
@AKSHITHA-CHILUKA @Snehsk

### CODE REVIEW

**Review by AKSHITHA-CHILUKA — APPROVED** [review]

**Comment by AKSHITHA-CHILUKA** [comment]
hey we asked for logo not your photo please change it

**Review by AKSHITHA-CHILUKA — CHANGES_REQUESTED** [review]
this is not this ss we asked for submit your build ss

**Comment by AkCode2005** [comment]
but this is the my project which i submitted 
@AKSHITHA-CHILUKA 
image

**Comment by AKSHITHA-CHILUKA** [comment]
Open your build and then take a ss for it and then submit that ss

**Pull request closed without merging**
