### PR TITLE
Added my repo file

### PR DESCRIPTION
**Pull request by shristirwt**

### CODE REVIEW

**Comment by aslams2020** [comment]
@shristirwt Is that your project ? i think it;s senior program manager's repository

**Comment by shristirwt** [comment]
Yes I asked him if I could submit the repo for hack web3conf and he permitted me to do so

**Comment by aslams2020** [comment]
> Yes I asked him if I could submit the repo for hack web3conf and he permitted me to do so

He might have misunderstood it, but it is not permissible, you have to add your own project or any idea related to web3

**Comment by shristirwt** [comment]
> > Yes I asked him if I could submit the repo for hack web3conf and he permitted me to do so
> 
> He might have misunderstood it, but it is not permissible, you have to add your own project or any idea related to web3

Okay I will ask him again and let you know

**Comment by aslams2020** [comment]
Please submit a new project idea, this PR cannot be merged as it is someone else's project.

**Pull request closed without merging**
