### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Gunpreet08**

### CODE REVIEW

**Review by Snehsk — CHANGES_REQUESTED** [review]
Please rename the screenshot as this format 

> Name-projectname-date

**Comment by Gunpreet08** [comment]
I have uploaded new with changes name

**Comment by Snehsk** [comment]
> I have uploaded new with changes name

Please remove previous image 
Keep only one image

**Comment by Gunpreet08** [comment]
@Snehsk I am not able to remove one , can u please help me how to do it

**Comment by Snehsk** [comment]
> @Snehsk I am not able to remove one , can u please help me how to do it

Close this pr nd create new one with same format

**Pull request closed without merging**
