### PR TITLE
Uploaded  my screenshot of Postman PR

### PR DESCRIPTION
**Pull request by N-SAI-HARIKA**
https://github.com/GSSoC24/Postman-Challenge/pull/4281

### CODE REVIEW

**Review by Tejashri-Taral — APPROVED** [review]

**Comment by vivekvardhan2810** [comment]
@Tejashri-Taral you have kept the labels wrong.

**Comment by N-SAI-HARIKA** [comment]
Hello, my name was not visible on the leaderboard, and my Postman pull request has not been merged yet. Could you please look into this? Thank you!

**Comment by Tejashri-Taral** [comment]
It's merged you will yable to see your name at 7PM

**Comment by N-SAI-HARIKA** [comment]
Okay, Thank you!

**Pull request merged**
