### PR TITLE
NIshant_plant_disease_detection_ 5/11/2024

### PR DESCRIPTION
**Pull request by nishant4500**
done
image

### CODE REVIEW

**Comment by nishant4500** [comment]
@Snehsk please can you merge my pull request !!

**Comment by Snehsk** [comment]
> @Snehsk please look into this

I m talking about this one
Screenshot_2024-11-05-23-27-30-75_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by nishant4500** [comment]
@Snehsk now can you please check

**Comment by Snehsk** [comment]
> @Snehsk now can you please check

Please delete previous image 
Keep one image only.

**Pull request closed without merging**
