### PR TITLE
Added my repo file

### PR DESCRIPTION
**Pull request by Ananya-vastare**

### CODE REVIEW

**Comment by Ananya-vastare** [comment]
@Snehsk  please review this and let me know if II need to make any changes thank you

**Review by Snehsk — CHANGES_REQUESTED** [review]
Please rename the screenshot as this format 

> Name-projectname-date

**Comment by Ananya-vastare** [comment]
@Snehsk I have made the changes please let me know if I need to do anything else

**Review by Snehsk — COMMENTED** [review]
🚀 Congratulations for your submission, your points will be reflected in the leaderboard till night.

**Pull request merged**
