### PR TITLE
add my repo file of project social media manager in web3 hack

### PR DESCRIPTION
**Pull request by Tanisha0708**
my project aims to store the data regarding social media in which it will store comments , likes , followers able tp see the posts , photoes , videos and varius hashtags and mentions . Through this project i am creating a basic structure of social media database which could easily be connected to frontend interface. Here i am managing the data of multiple users, their followers , interests and public activity on the social media platform which includes postlikes ,comments , commentlikes , hashtag followed ,bookmarks and many more... Through our SQL query i have shown a clear cut description of connection and inter relation between different activities on social media. Here i have tried to fetch and store the data in its true storage form into this database like (img/videos in url) With my true efforts and research we have tried to give a simple and more exact view of a basic social interconnecting site. once go through my pr

### CODE REVIEW

**Comment by Tanisha0708** [comment]
@AKSHITHA-CHILUKA  once go through this pr

**Review by AKSHITHA-CHILUKA — CHANGES_REQUESTED** [review]
open a new pr you just need to add the ss @Tanisha0708

**Comment by Tanisha0708** [comment]
Screenshot 2024-11-08 135757

**Comment by AKSHITHA-CHILUKA** [comment]
Open a new pr and submit it @Tanisha0708

**Pull request closed without merging**
