### PR TITLE
added my repo file

### PR DESCRIPTION
**Pull request by Nayan2003**

### CODE REVIEW

**Review by Snehsk — CHANGES_REQUESTED** [review]
Hi could you please rename the screenshot as this format 

> Name-projectname-date

**Comment by Snehsk** [comment]
> Ohk maam ☺️

Keep only one image so delete previous one.

**Comment by Nayan2003** [comment]
Done ma'am

**Review by Snehsk — APPROVED** [review]

**Review by Snehsk — COMMENTED** [review]
🚀 Congratulations for your submission, your points will be reflected in the leaderboard till tomorrow

**Pull request merged**
