### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Tanisha0708**

### CODE REVIEW

**Comment by Tanisha0708** [comment]
Screenshot 2024-11-08 135757

**Comment by Tanisha0708** [comment]
@sanjay-kv once go through this pr

**Comment by Tanisha0708** [comment]
@AKSHITHA-CHILUKA once go through this pr

**Comment by AKSHITHA-CHILUKA** [comment]
image
upload a .png  file @Tanisha0708

**Comment by Tanisha0708** [comment]
Screenshot 2024-11-08 135748

**Comment by Tanisha0708** [comment]
@AKSHITHA-CHILUKA  please check once

**Comment by Tanisha0708** [comment]
@AKSHITHA-CHILUKA  once enter in load diff there are some changes did

**Comment by Tanisha0708** [comment]
@AKSHITHA-CHILUKA  i have uploaded .png file . are you facing any issue regarding this file .?

**Pull request closed without merging**
