### PR TITLE
Added my repo

### PR DESCRIPTION
**Pull request by SathvigaaBharathi**

### CODE REVIEW

**Comment by aslams2020** [comment]
Create a new PR.

**Comment by aslams2020** [comment]
Share the Screenshot of the Dashboard here in the comment. This issue with you has been happening from last 2-3 days

**Comment by aslams2020** [comment]
I will review and merge this PR then 

@SathvigaaBharathi

**Comment by SathvigaaBharathi** [comment]
SathvigaaBharathi-Decentralized voting system-9 Nov

**Comment by aslams2020** [comment]
OKay!

**Comment by aslams2020** [comment]
@SathvigaaBharathi Congrats on your submission. Your points will be reflected in the next leaderboard update

**Comment by SathvigaaBharathi** [comment]
Thanks

**Pull request merged**
