### PR TITLE
Added BUIDL Screenshot to Repo

### PR DESCRIPTION
**Pull request by KiranBaliga**
Please review the screenshot

### CODE REVIEW

**Comment by KiranBaliga** [comment]
Project Name: OtakuChain

@sanjay-kv please merge the PR, assign all the labels. Looking forward to the web3 conf badge.
Thank you !!

**Comment by KiranBaliga** [comment]
@Snehsk please review the PR and action accordingly. Thank you!

**Review by AKSHITHA-CHILUKA — CHANGES_REQUESTED** [review]
please rename your file name 
Your name - project title - date

**Comment by KiranBaliga** [comment]
@AKSHITHA-CHILUKA changes have been made as requested

**Review by AKSHITHA-CHILUKA — APPROVED** [review]

**Pull request merged**
