### PR TITLE
Devanshu1603-calculator-05/11/2024

### PR DESCRIPTION
**Pull request by Devanshu1603**
i have successfully registered to the Hack-Web3Conf . My Github :- https://github.com/Devanshu1603. please merge the PR .

### CODE REVIEW

**Comment by Devanshu1603** [comment]
@aslams2020  please review the PR and merge it accordingly.

**Comment by Devanshu1603** [comment]
@aslams2020  please merge my PR such that i got the points on leaderboard

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Please Rename the screenshot as `yourname-projectname-date`

**Comment by Devanshu1603** [comment]
@aslams2020  Done

**Comment by aslams2020** [comment]
Rename the screenshot

Screenshot_2024-11-05-17-35-46-83_40deb401b9ffe8e1df2f1cc5ba480b12

So that, it will not create confusion

**Comment by Devanshu1603** [comment]
are you asking me to change the name of file

**Comment by aslams2020** [comment]
Yeah

**Comment by Devanshu1603** [comment]
are you asking me to change the name of file

**Comment by Devanshu1603** [comment]
@aslams2020  unable to do that , please help

**Comment by aslams2020** [comment]
You can close this PR, and create a new PR with the renamed image. It'll be easy for you

**Comment by Devanshu1603** [comment]
okay

**Pull request closed without merging**
