### PR TITLE
Added My Project File

### PR DESCRIPTION
**Pull request by AkCode2005**
My project is based on Blockchain. Which I submitted in HackWeb3Conf
Please Go through with it.
@vansh-codes

### CODE REVIEW

**Review by Snehsk — CHANGES_REQUESTED** [review]
Please rename the screenshot as this format 

> Name-projectname-date

**Comment by AkCode2005** [comment]
Please Go through this i made the changes
@Snehsk

**Review by Snehsk — CHANGES_REQUESTED** [review]
Please delete this one (previous file)
Keep only one image

**Comment by AkCode2005** [comment]
Can you please tell how to do it 
@Snehsk

**Pull request closed without merging**
